codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/
    carryforward: true

ignore:
  - "backend/*/migrations/*"
  - "backend/*/tests/*"
  - "backend/manage.py"
  - "backend/recipe_project/wsgi.py"
  - "backend/recipe_project/asgi.py"
  - "frontend/src/index.js"
  - "frontend/src/reportWebVitals.js"
  - "frontend/src/**/*.test.js"
  - "frontend/src/setupTests.js"
