# Generated by Django 4.2.7 on 2025-10-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['category', '-created_at'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('baking_bread', 'Baking and Bread'), ('breakfast', 'Breakfast'), ('desserts', 'Desserts'), ('dinner', 'Dinner'), ('drinks', 'Drinks'), ('international', 'International'), ('lunch', 'Lunch')], db_index=True, default='dinner', help_text='Recipe category', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category', '-created_at'], name='recipe_category_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('category__in', ['appetizers', 'baking_bread', 'breakfast', 'desserts', 'dinner', 'drinks', 'international', 'lunch'])), name='recipe_category_valid'),
        ),
    ]
