# Generated by Django 4.2.7 on 2025-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_recipe_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list, help_text='List of dietary tags (e.g., vegan, gluten-free)'),
        ),
    ]
