# Generated by Django 4.2.7 on 2025-11-05 16:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_favorite_userprofile_recipe_is_private_recipe_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the shopping list (e.g., 'Week of Jan 1-7')", max_length=200)),
                ('start_date', models.DateField(blank=True, help_text='Start date of meal plan period', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of meal plan period', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this shopping list is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this shopping list was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this shopping list was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this shopping list', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping Lists',
                'db_table': 'recipes_shoppinglist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for this meal')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], db_index=True, help_text='Type of meal (breakfast, lunch, dinner)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order when multiple recipes are assigned to same meal', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this meal', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this meal plan entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this meal plan entry was last updated')),
                ('recipe', models.ForeignKey(blank=True, help_text='Recipe assigned to this meal slot (null for empty slot)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='recipes.recipe')),
                ('user', models.ForeignKey(help_text='User who created this meal plan', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'db_table': 'recipes_mealplan',
                'ordering': ['date', 'meal_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(db_index=True, help_text='Name of the ingredient', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the ingredient', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(help_text="Unit of measurement (e.g., 'cups', 'lbs', 'oz', 'grams')", max_length=50)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy & Eggs'), ('meat', 'Meat & Seafood'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('canned', 'Canned Goods'), ('frozen', 'Frozen'), ('beverages', 'Beverages'), ('condiments', 'Condiments & Sauces'), ('spices', 'Spices & Seasonings'), ('snacks', 'Snacks'), ('other', 'Other')], db_index=True, default='other', help_text='Category for organizing shopping list', max_length=20)),
                ('is_checked', models.BooleanField(default=False, help_text='Whether this item has been checked off the list')),
                ('source_recipes', models.JSONField(blank=True, default=list, help_text='List of recipe IDs that contributed to this item')),
                ('is_custom', models.BooleanField(default=False, help_text='True if manually added, False if from recipes')),
                ('notes', models.CharField(blank=True, help_text='Optional notes for this item', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this item was last updated')),
                ('shopping_list', models.ForeignKey(help_text='Shopping list this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.shoppinglist')),
            ],
            options={
                'verbose_name': 'Shopping List Item',
                'verbose_name_plural': 'Shopping List Items',
                'db_table': 'recipes_shoppinglistitem',
                'ordering': ['category', 'order', 'ingredient_name'],
                'indexes': [models.Index(fields=['shopping_list', 'category'], name='shopitem_list_category_idx'), models.Index(fields=['shopping_list', 'is_checked'], name='shopitem_list_checked_idx'), models.Index(fields=['category', 'order'], name='shopitem_cat_order_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='shoppingitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 0)), name='shoppingitem_order_positive'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', '-created_at'], name='shoppinglist_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'is_active'], name='shoppinglist_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date'], name='mealplan_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date', 'meal_type'], name='mealplan_user_date_meal_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['date', 'meal_type', 'order'], name='mealplan_date_meal_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(check=models.Q(('meal_type__in', ['breakfast', 'lunch', 'dinner'])), name='mealplan_meal_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 0)), name='mealplan_order_positive'),
        ),
    ]
